"""
Turning verdicts into explanations a human can act on.

Jury concern #2 was "can it use explainable AI?" This module is the answer's
first half, and it exists before any model does — deliberately.

The rule layer is explainable *by construction*: the evidence that produced a
verdict is the same evidence that explains it, so no post-hoc attribution is
needed and none can disagree with the decision. When the ML layer arrives in
Phase 3, SHAP will produce additive feature contributions in the same shape as
the rule layer's additive evidence contributions, and both render through the
functions here.

That ordering matters and is worth stating to a reviewer: an explanation
generated by a *separate* mechanism from the decision can be wrong about its own
model. An explanation that is a readout of the decision itself cannot.
"""

from __future__ import annotations

from typing import Any

from apix.engine.verdict import Classification, Verdict

#: What each label means, in one line, for an operator who is not the architect.
LABEL_MEANING: dict[Classification, str] = {
    Classification.ACTIVE: "documented, owned, and carrying real traffic",
    Classification.DEPRECATED: "announced as retiring but still responding",
    Classification.ORPHANED: "genuinely in use, but nobody owns it",
    Classification.ZOMBIE: "no meaningful use and largely invisible to the organisation",
}

#: What the operator should do about it.
LABEL_ACTION: dict[Classification, str] = {
    Classification.ACTIVE: "No action. Continue monitoring.",
    Classification.DEPRECATED: (
        "Confirm the retirement plan has a date. Deprecated endpoints that never "
        "get removed are how zombies are created."
    ),
    Classification.ORPHANED: (
        "Assign an owner. Do NOT schedule removal — this endpoint carries real "
        "traffic and disabling it would cause an outage."
    ),
    Classification.ZOMBIE: (
        "Candidate for Safe Kill. Blast radius must be computed and an approval "
        "recorded before any shutdown begins."
    ),
}

_BAR_WIDTH = 5


#: What each label means when the evidence behind it is incomplete. The
#: full-evidence wording asserts things a partial scan cannot know — telling an
#: operator an endpoint "carries real traffic" when no traffic was ever measured
#: is exactly the kind of confident fabrication this system exists to avoid.
PARTIAL_MEANING: dict[Classification, str] = {
    Classification.ACTIVE: "nothing in the available evidence suggests decay",
    Classification.DEPRECATED: "declared obsolete in the specification",
    Classification.ORPHANED: "no owning team could be identified",
    Classification.ZOMBIE: "undocumented and unmaintained on the evidence available",
}

PARTIAL_ACTION: dict[Classification, str] = {
    Classification.ACTIVE: "No action on this evidence.",
    Classification.DEPRECATED: (
        "Confirm the retirement plan has a date. Deprecated endpoints that "
        "never get removed are how zombies are created."
    ),
    Classification.ORPHANED: (
        "Identify an owner. Whether it is still in use is unknown from this "
        "scan."
    ),
    Classification.ZOMBIE: (
        "Investigate. NOT a removal candidate on this evidence — usage was "
        "never measured, and a repository cannot show what a service serves."
    ),
}


def explain(v: Verdict, *, indent: str = "") -> str:
    """Render one verdict as a human-readable explanation block."""
    lines: list[str] = []
    bar = "#" * v.risk_score + "." * (_BAR_WIDTH - v.risk_score)
    partial = v.is_partial

    lines.append(f"{indent}[{bar}] {v.endpoint_id}")

    if not v.is_determinate:
        lines.append(
            f"{indent}        verdict : UNDETERMINED — no evidence was available; "
            "this endpoint was enumerated, not assessed"
        )
        lines.append(f"{indent}        action  : Connect more sources.")
        return "\n".join(lines)

    if not v.supports_lifecycle_claim:
        # Report what was observed rather than forcing a lifecycle label that
        # the available evidence cannot support.
        lines.append(
            f"{indent}        status  : FINDINGS ONLY — lifecycle cannot be "
            "determined without usage data"
        )
        for statement in v.findings:
            lines.append(f"{indent}          · {statement}")
        missing = ", ".join(sorted(_UNSEEN_SOURCES - v.sources_consulted))
        lines.append(f"{indent}        unknown : {missing} not consulted")
        lines.append(
            f"{indent}        action  : Triage on these findings. Connect a "
            "traffic source before any removal decision."
        )
        return "\n".join(lines)

    meaning = (PARTIAL_MEANING if partial else LABEL_MEANING)[v.label]
    qualifier = " on partial evidence" if partial else ""
    lines.append(
        f"{indent}        verdict : {v.label.value} "
        f"({v.confidence:.0%} confidence{qualifier}) — {meaning}"
    )

    support = v.supporting_reasons
    oppose = v.opposing_reasons

    if support:
        lines.append(f"{indent}        because :")
        for r in support:
            lines.append(
                f"{indent}          + {r.statement}  "
                f"[{r.evidence_source}, +{r.contribution:.1f}]"
            )
    if oppose:
        lines.append(f"{indent}        despite :")
        for r in oppose:
            lines.append(
                f"{indent}          - {r.statement}  "
                f"[{r.evidence_source}, {r.contribution:.1f}]"
            )

    if partial:
        unseen = ", ".join(sorted(_UNSEEN_SOURCES - v.sources_consulted))
        if unseen:
            lines.append(
                f"{indent}        unknown : {unseen} not consulted — "
                f"{len(v.abstained)} rule(s) abstained"
            )

    lines.append(
        f"{indent}        action  : "
        f"{(PARTIAL_ACTION if partial else LABEL_ACTION)[v.label]}"
    )
    return "\n".join(lines)


#: Every source a verdict might have been denied. Used to name what was missing.
_UNSEEN_SOURCES = frozenset(
    {"GATEWAY", "OPENAPI", "TRAFFIC", "CODE", "DNS", "CICD"}
)


def one_line(v: Verdict) -> str:
    """Compact single-line summary, for dense listings."""
    top = v.supporting_reasons[:3]
    why = "; ".join(r.statement for r in top) if top else "no positive evidence"
    return f"{v.label.value:<11} {v.confidence:>4.0%}  {v.endpoint_id}  — {why}"


def audit_entry(v: Verdict) -> dict[str, Any]:
    """The verdict in the shape the audit log stores.

    Every field an auditor needs to reconstruct the decision without access to
    the system that made it: the inputs that fired, their signed contributions,
    the scores for every class considered (not just the winner), and which
    component decided.
    """
    return {
        "endpoint_id": v.endpoint_id,
        "label": v.label.value,
        "confidence": round(v.confidence, 4),
        "decided_by": v.decided_by,
        "risk_score": v.risk_score,
        "all_class_scores": v.scores,
        "evidence": [
            {
                "key": r.key,
                "statement": r.statement,
                "source": r.evidence_source,
                "contribution": r.contribution,
            }
            for r in v.reasons
        ],
        "recommended_action": LABEL_ACTION[v.label],
        "actionable": v.is_actionable,
    }


def summarise(verdicts: list[Verdict]) -> str:
    """Distribution of verdicts across the estate."""
    counts: dict[str, int] = {}
    for v in verdicts:
        counts[v.label.value] = counts.get(v.label.value, 0) + 1

    total = len(verdicts) or 1
    lines = ["Classification summary", ""]
    for cls in Classification:
        n = counts.get(cls.value, 0)
        pct = 100.0 * n / total
        lines.append(
            f"  {cls.value:<11} {n:>3}  ({pct:4.1f}%)  {'#' * n}"
        )

    actionable = sum(1 for v in verdicts if v.is_actionable)
    lines.append("")
    lines.append(
        f"  {actionable} endpoint(s) are Safe Kill candidates; "
        f"{counts.get('ORPHANED', 0)} need an owner but must not be removed."
    )
    return "\n".join(lines)
